version: "3.5"
services:
  shellcode:
    build: .
    restart: always
    read_only: true
    ports:
      - "6001:6001"
    logging:
      driver: "json-file"
      options:
          max-file: "1"
          max-size: "5m"
    #healthcheck:
    #  test: "python3 /chal/exploit.py"
    #  timeout: 15s
    #  interval: 3m
    #  retries: 2

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: shellcode
